Solucionando errores:
ERROR in src\app\components\post-new\post-new.component.html(62,15): : Property 'resetVar' does not exist on type 'PostNewComponent'.
src\app\components\post-new\post-new.component.html(11,42): : Property 'insert' does not exist on type 'PostEditComponent'.
src\app\components\post-new\post-new.component.html(62,15): : Property 'resetVar' does not exist on type 'PostEditComponent'.